"""empty message

Revision ID: 2fbfe8342575
Revises: 706641e92fa3
Create Date: 2024-05-08 23:18:14.549047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbfe8342575'
down_revision = '706641e92fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('departure_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint('packages_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients_table', ['client_id'], ['client_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('packages_table_ibfk_1', 'clients_table', ['client_id'], ['client_id'], ondelete='CASCADE')
        batch_op.alter_column('departure_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
