"""empty message

Revision ID: 4e9a170283ba
Revises: c98275fb22f1
Create Date: 2024-03-15 20:41:54.361569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9a170283ba'
down_revision = 'c98275fb22f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_class', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.drop_column('travel_class')

    # ### end Alembic commands ###
