"""empty message

Revision ID: 6528c41dbe17
Revises: 1a0292b4b6b0
Create Date: 2024-05-06 20:14:51.599334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6528c41dbe17'
down_revision = '1a0292b4b6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports_table', schema=None) as batch_op:
        batch_op.alter_column('links_count',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports_table', schema=None) as batch_op:
        batch_op.alter_column('links_count',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
