"""empty message

Revision ID: 9b05aea33e6f
Revises: 1f4786104b7e
Create Date: 2024-04-06 23:42:43.131748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b05aea33e6f'
down_revision = '1f4786104b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links_count', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports_table', schema=None) as batch_op:
        batch_op.drop_column('links_count')

    # ### end Alembic commands ###
