"""empty message

Revision ID: 9e1f95782e4d
Revises: e5bed500d97b
Create Date: 2024-04-07 00:05:35.422240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1f95782e4d'
down_revision = 'e5bed500d97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports_table',
    sa.Column('airport_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('iata_code', sa.String(length=5), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('links_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('airport_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airports_table')
    # ### end Alembic commands ###
