"""empty message

Revision ID: e5bed500d97b
Revises: 9b05aea33e6f
Create Date: 2024-04-07 00:05:11.165636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5bed500d97b'
down_revision = '9b05aea33e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airports_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports_table',
    sa.Column('airport_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('iata_code', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('links_count', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('airport_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
